# Generated by Django 5.2.5 on 2025-09-10 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="total_playtime",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
